import type { UniteStructurelle } from "./types"

export const STRUCTURE_DATA: UniteStructurelle[] = [
  {
    id: "reseau-fiinor",
    nom: "Réseau FIINOR",
    typeId: "reseau",
    ville: "Conakry",
    pays: "Guinée",
    flag: "🇬🇳",
    effectif: 7840,
    score: 94.2,
    trend: "+2.1%",
    children: [
      {
        id: "lycee-moderne-conakry",
        nom: "Lycée Moderne Conakry",
        typeId: "etablissement",
        ville: "Conakry",
        pays: "Guinée",
        flag: "🇬🇳",
        effectif: 1240,
        score: 96.5,
        trend: "+2.3%",
        children: [
          {
            id: "dept-sciences-lmc",
            nom: "Département Sciences",
            typeId: "departement",
            effectif: 480,
            score: 97.1,
            trend: "+1.8%",
            children: [
              {
                id: "terminale-s1",
                nom: "Terminale S1",
                typeId: "classe",
                effectif: 42,
                score: 98.2,
                trend: "+3.1%",
                children: [],
              },
              {
                id: "terminale-s2",
                nom: "Terminale S2",
                typeId: "classe",
                effectif: 38,
                score: 96.8,
                trend: "+1.5%",
                children: [],
              },
              {
                id: "premiere-s1",
                nom: "Première S1",
                typeId: "classe",
                effectif: 45,
                score: 95.4,
                trend: "+0.9%",
                children: [],
              },
            ],
          },
          {
            id: "dept-lettres-lmc",
            nom: "Département Lettres",
            typeId: "departement",
            effectif: 390,
            score: 94.8,
            trend: "+2.7%",
            children: [
              {
                id: "terminale-l1",
                nom: "Terminale L1",
                typeId: "classe",
                effectif: 40,
                score: 95.0,
                trend: "+2.0%",
                children: [],
              },
              {
                id: "premiere-l1",
                nom: "Première L1",
                typeId: "classe",
                effectif: 44,
                score: 94.3,
                trend: "+1.4%",
                children: [],
              },
            ],
          },
        ],
      },
      {
        id: "aether-int-school",
        nom: "Aether Int. School",
        typeId: "etablissement",
        ville: "Dubaï",
        pays: "Émirats Arabes Unis",
        flag: "🇦🇪",
        effectif: 890,
        score: 93.1,
        trend: "+1.2%",
        children: [
          {
            id: "faculte-ingenierie-aether",
            nom: "Faculté d'Ingénierie",
            typeId: "faculte",
            effectif: 450,
            score: 94.0,
            trend: "+1.5%",
            children: [
              {
                id: "dept-info-aether",
                nom: "Département Informatique",
                typeId: "departement",
                effectif: 220,
                score: 95.2,
                trend: "+2.0%",
                children: [
                  {
                    id: "l3-info-aether",
                    nom: "Licence 3 Informatique",
                    typeId: "classe",
                    effectif: 55,
                    score: 96.1,
                    trend: "+1.8%",
                    children: [],
                  },
                ],
              },
              {
                id: "dept-genie-civil-aether",
                nom: "Département Génie Civil",
                typeId: "departement",
                effectif: 230,
                score: 92.8,
                trend: "+1.0%",
                children: [],
              },
            ],
          },
          {
            id: "faculte-gestion-aether",
            nom: "Faculté de Gestion",
            typeId: "faculte",
            effectif: 440,
            score: 92.2,
            trend: "+0.9%",
            children: [],
          },
        ],
      },
      {
        id: "univ-gam-abdel",
        nom: "Univ. Gam Al Abdel Nasser",
        typeId: "etablissement",
        ville: "Conakry",
        pays: "Guinée",
        flag: "🇬🇳",
        effectif: 3400,
        score: 88.5,
        trend: "+0.8%",
        children: [
          {
            id: "faculte-droit-gam",
            nom: "Faculté de Droit",
            typeId: "faculte",
            effectif: 1200,
            score: 87.4,
            trend: "+0.5%",
            children: [
              {
                id: "dept-droit-prive",
                nom: "Département Droit Privé",
                typeId: "departement",
                effectif: 600,
                score: 88.1,
                trend: "+0.7%",
                children: [],
              },
              {
                id: "dept-droit-public",
                nom: "Département Droit Public",
                typeId: "departement",
                effectif: 600,
                score: 86.7,
                trend: "+0.3%",
                children: [],
              },
            ],
          },
          {
            id: "faculte-medecine-gam",
            nom: "Faculté de Médecine",
            typeId: "faculte",
            effectif: 2200,
            score: 89.2,
            trend: "+1.1%",
            children: [],
          },
        ],
      },
      {
        id: "inst-superieur-dakar",
        nom: "Institut Supérieur Dakar",
        typeId: "etablissement",
        ville: "Dakar",
        pays: "Sénégal",
        flag: "🇸🇳",
        effectif: 310,
        score: 91.2,
        trend: "+1.8%",
        children: [
          {
            id: "dept-finance-isd",
            nom: "Département Finance",
            typeId: "departement",
            effectif: 160,
            score: 92.0,
            trend: "+2.2%",
            children: [],
          },
          {
            id: "dept-marketing-isd",
            nom: "Département Marketing",
            typeId: "departement",
            effectif: 150,
            score: 90.4,
            trend: "+1.4%",
            children: [],
          },
        ],
      },
    ],
  },
]
